# Example configuration for the Pingora JWT Proxy

issuer_url: "https://dev-mggbo2rpkt6xfkix.us.auth0.com/" # Required: OIDC provider's issuer URL
# Optional: Uncomment and set if you want to specify the JWKS URI directly,
# bypassing discovery from the issuer_url.
jwks_uri: "https://dev-mggbo2rpkt6xfkix.us.auth0.com/.well-known/jwks.json"
client_id: "https://dev-mggbo2rpkt6xfkix.us.auth0.com/api/v2/" # Required: Your application's client ID

algorithms: # Optional: Defaults to ["RS256"] in nila-oidc
  - "RS256"
  - "HS256"

# leeway_seconds: 60 # Optional: Defaults to 60 seconds

# If your OIDC provider's JWKS endpoint is sending a Cache-Control: max-age=15 header in its HTTP response, then the below value will be overridden by that value.
cache_ttl_seconds: 3600 # Optional: Default fallback TTL for JWKS cache in seconds (e.g., 1 hour). Library default is 24h.

validate_nonce: false # Optional: Defaults to true. Set to false to disable nonce validation for this proxy.

claim_assertions: # Optional section for custom claim validations
  required_claims: # Optional: List of claim names that MUST be present in the token
    - "scope" # Assuming your token might have this
  exact_match_claims: # Optional: Map of claim_name: expected_value
    "sub": "NHhIYJ3ndvA3Qv25Iqoy7HPKjkY7r3gc@clients"
    "scope": "read:client_grants"

logging: # New logging configuration section
  output: "stdout"        # Example: "stdout" or "file"
  level: "info"           # Can be "error", "warn", "info", "debug", "trace"
  format: "json"          # Example: "json" or "text"
  pretty_print_logs: false # Example: true or false

listen_addr: "0.0.0.0:6188"
upstream_addr: "httpbin.io:80" # Example upstream
